agents:
  queue: hosted

cache:
  paths:
    - ".buildkite-cache/mise/data"
    - ".buildkite-cache/mise/cache"
    - ".buildkite-cache/mise/state"
  size: "20g"
  name: "mise-cache"

env:
  MISE_YES: "1"
  MISE_TRUSTED_CONFIG_PATHS: /buildkite/builds
  MISE_DATA_DIR: ".buildkite-cache/mise/data"
  MISE_CACHE_DIR: ".buildkite-cache/mise/cache"
  MISE_STATE_DIR: ".buildkite-cache/mise/state"

steps:
  - label: ":typescript: Typecheck"
    command: pnpm install && pnpm typecheck

  - label: ":test_tube: Test"
    command: pnpm install && pnpm test

  - label: ":package: Build"
    command: pnpm install && pnpm build

  - wait

  - block: ":rocket: Deploy to Staging"
    if: build.pull_request.id != null

  - label: ":fly: Deploy Staging"
    if: build.pull_request.id != null
    command: flyctl deploy --config fly.staging.toml --remote-only
    secrets:
      - FLY_API_TOKEN_STAGING

  - wait

  - label: ":fly: Deploy Production"
    branches: main
    command: flyctl deploy --config fly.toml --remote-only
    secrets:
      - FLY_API_TOKEN_PRODUCTION
